
export default function TermsPage() {
  return (
    <div className="bg-background py-20">
      <div className="max-w-4xl mx-auto px-6">
        <h1 className="font-headline text-5xl font-bold mb-8">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Effective Date: March 2024</p>
        
        <div className="space-y-8 text-muted-foreground">
          <section>
            <h2 className="text-2xl font-bold text-off-white mb-4">1. No Financial Advice</h2>
            <p>Atlas Wealth OS is a software platform for data management and visualization. Atlas Wealth Systems does not provide financial, legal, or tax advice. All informational snippets and insights generated by the system are for informational purposes only.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-off-white mb-4">2. Account Responsibility</h2>
            <p>Users are responsible for maintaining the security of their decryption keys and authentication credentials. Loss of access keys may result in permanent loss of access to encrypted data.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-off-white mb-4">3. Service Availability</h2>
            <p>While we strive for 99.99% uptime, we do not guarantee uninterrupted access to the platform due to the nature of global financial network integrations.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
